export const LIST_ACTION_TYPES = {
  LIST_LIST_REQUEST: "LIST_LIST_REQUEST",
  LIST_LIST_SUCCESS: "LIST_LIST_SUCCESS",
  LIST_LIST_FAILED: "LIST_LIST_FAILED",

  LIST_CREATE_REQUEST: "LIST_CREATE_REQUEST",
  LIST_CREATE_SUCCESS: "LIST_CREATE_SUCCESS",
  LIST_CREATE_FAILED: "LIST_CREATE_FAILED",
  LIST_CREATE_RESET: "LIST_CREATE_RESET",

  LIST_DETAILS_REQUEST: "LIST_DETAILS_REQUEST",
  LIST_DETAILS_SUCCESS: "LIST_DETAILS_SUCCESS",
  LIST_DETAILS_FAILED: "LIST_DETAILS_FAILED",

  LIST_UPDATE_REQUEST: "LIST_UPDATE_REQUEST",
  LIST_UPDATE_SUCCESS: "LIST_UPDATE_SUCCESS",
  LIST_UPDATE_FAILED: "LIST_UPDATE_FAILED",
  LIST_UPDATE_RESET: "LIST_UPDATE_RESET",

  LIST_DELETE_REQUEST: "LIST_DELETE_REQUEST",
  LIST_DELETE_SUCCESS: "LIST_DELETE_SUCCESS",
  LIST_DELETE_FAILED: "LIST_DELETE_FAILED",
  LIST_DELETE_RESET: "LIST_DELETE_RESET",

  LIST_RESET_STATUS: "LIST_RESET_STATUS",
};
